# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='genre',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
