# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0005_auto_20170717_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='content',
            field=models.CharField(max_length=400),
        ),
    ]
