# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0006_auto_20170718_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='content',
            field=models.TextField(),
        ),
    ]
