# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0007_auto_20170718_0451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='author',
        ),
        migrations.AddField(
            model_name='branch',
            name='id',
            field=models.AutoField(auto_created=True, default='0', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
