# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 05:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stories', '0008_auto_20170718_0530'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='author',
            field=models.OneToOneField(default='none', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
