# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 07:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0009_branch_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='author',
        ),
    ]
