# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 00:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0011_auto_20170720_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=False, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='branch',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
