# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 00:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0012_auto_20170720_0019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='author',
        ),
    ]
